[14:20:45.886] THREE.WebGLRenderer 56
[14:20:47.691] ({
mesh_use_embedded_materials:false,
scale:{y:1, x:1, z:1}, 
frame_locked:false, 
color:{a:1, r:0, b:0, g:1}, 
text:"", 
pose:{
	position:{y:0, x:0, z:0}, 
	orientation:{y:0, x:0, z:0, w:1}}, 
mesh_resource:"", 
header:{stamp:{secs:1374700821, nsecs:725229501}, frame_id:"/my_frame", seq:545585}, 
colors:[], 
points:[], 
action:0, 
lifetime:{secs:0, nsecs:0}, 
ns:"basic_shapes", 
type:2, 
id:0})


[14:20:49.321] ({mesh_use_embedded_materials:false, scale:{y:1, x:1, z:1}, frame_locked:false, color:{a:1, r:0, b:0, g:1}, text:"", pose:{position:{y:0, x:0, z:0}, orientation:{y:0, x:0, z:0, w:1}}, mesh_resource:"", header:{stamp:{secs:1374700822, nsecs:725295758}, frame_id:"/my_frame", seq:545586}, colors:[], points:[], action:0, lifetime:{secs:0, nsecs:0}, ns:"basic_shapes", type:0, id:0})
[14:20:49.362] ({mesh_use_embedded_materials:false, scale:{y:1, x:1, z:1}, frame_locked:false, color:{a:1, r:0, b:0, g:1}, text:"", pose:{position:{y:0, x:0, z:0}, orientation:{y:0, x:0, z:0, w:1}}, mesh_resource:"", header:{stamp:{secs:1374700823, nsecs:725211712}, frame_id:"/my_frame", seq:545587}, colors:[], points:[], action:0, lifetime:{secs:0, nsecs:0}, ns:"basic_shapes", type:3, id:0})
[14:20:50.089] ({mesh_use_embedded_materials:false, scale:{y:1, x:1, z:1}, frame_locked:false, color:{a:1, r:0, b:0, g:1}, text:"", pose:{position:{y:0, x:0, z:0}, orientation:{y:0, x:0, z:0, w:1}}, mesh_resource:"", header:{stamp:{secs:1374700824, nsecs:725221096}, frame_id:"/my_frame", seq:545588}, colors:[], points:[], action:0, lifetime:{secs:0, nsecs:0}, ns:"basic_shapes", type:1, id:0})
[14:20:51.083] ({mesh_use_embedded_materials:false, scale:{y:1, x:1, z:1}, frame_locked:false, color:{a:1, r:0, b:0, g:1}, text:"", pose:{position:{y:0, x:0, z:0}, orientation:{y:0, x:0, z:0, w:1}}, mesh_resource:"", header:{stamp:{secs:1374700825, nsecs:725212112}, frame_id:"/my_frame", seq:545589}, colors:[], points:[], action:0, lifetime:{secs:0, nsecs:0}, ns:"basic_shapes", type:2, id:0})
[14:20:52.068] ({mesh_use_embedded_materials:false, scale:{y:1, x:1, z:1}, frame_locked:false, color:{a:1, r:0, b:0, g:1}, text:"", pose:{position:{y:0, x:0, z:0}, orientation:{y:0, x:0, z:0, w:1}}, mesh_resource:"", header:{stamp:{secs:1374700826, nsecs:725220598}, frame_id:"/my_frame", seq:545590}, colors:[], points:[], action:0, lifetime:{secs:0, nsecs:0}, ns:"basic_shapes", type:0, id:0})
[14:20:53.235] ({mesh_use_embedded_materials:false, scale:{y:1, x:1, z:1}, frame_locked:false, color:{a:1, r:0, b:0, g:1}, text:"", pose:{position:{y:0, x:0, z:0}, orientation:{y:0, x:0, z:0, w:1}}, mesh_resource:"", header:{stamp:{secs:1374700827, nsecs:725168476}, frame_id:"/my_frame", seq:545591}, colors:[], points:[], action:0, lifetime:{secs:0, nsecs:0}, ns:"basic_shapes", type:3, id:0})
[14:20:54.136] ({mesh_use_embedded_materials:false, scale:{y:1, x:1, z:1}, frame_locked:false, color:{a:1, r:0, b:0, g:1}, text:"", pose:{position:{y:0, x:0, z:0}, orientation:{y:0, x:0, z:0, w:1}}, mesh_resource:"", header:{stamp:{secs:1374700828, nsecs:725405278}, frame_id:"/my_frame", seq:545592}, colors:[], points:[], action:0, lifetime:{secs:0, nsecs:0}, ns:"basic_shapes", type:1, id:0})
[14:20:55.169] ({mesh_use_embedded_materials:false, scale:{y:1, x:1, z:1}, frame_locked:false, color:{a:1, r:0, b:0, g:1}, text:"", pose:{position:{y:0, x:0, z:0}, orientation:{y:0, x:0, z:0, w:1}}, mesh_resource:"", header:{stamp:{secs:1374700829, nsecs:726049793}, frame_id:"/my_frame", seq:545593}, colors:[], points:[], action:0, lifetime:{secs:0, nsecs:0}, ns:"basic_shapes", type:2, id:0})
[14:20:56.116] ({mesh_use_embedded_materials:false, scale:{y:1, x:1, z:1}, frame_locked:false, color:{a:1, r:0, b:0, g:1}, text:"", pose:{position:{y:0, x:0, z:0}, orientation:{y:0, x:0, z:0, w:1}}, mesh_resource:"", header:{stamp:{secs:1374700830, nsecs:725333572}, frame_id:"/my_frame", seq:545594}, colors:[], points:[], action:0, lifetime:{secs:0, nsecs:0}, ns:"basic_shapes", type:0, id:0})
